apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@ruchij.com

    privateKeySecretRef:
      name: lets-encrypt

    # Uses ambient AWS credentials
    solvers:
      - dns01:
          route53:
            region: ap-southeast-2
