apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ruchira088@gmail.com
    privateKeySecretRef:
      name: lets-encrypt
    dns01:
      providers:
        - name: route53-dns
          route53:
            region: ap-southeast-2
            accessKeyID: <AWS ACCESS_KEY_ID>
            secretAccessKeySecretRef:
              name: cert-manager-secrets
              key: SECRET_ACCESS_KEY