apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ruchira088@gmail.com

    privateKeySecretRef:
      name: lets-encrypt

    # Uses ambient AWS credentials
    dns01:
      providers:
        - name: route53-dns
          route53:
            region: ap-southeast-2
