version: 2
jobs:
  build:
    docker:
      - image: node

    working_directory: ~/repository

    steps:
      - checkout

      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package.json" }}
            - node_modules_cache

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node_modules_cache_{{ checksum "package.json" }}

      - run: npm test