apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ name }}-tls-certificate
spec:
  secretName: {{ tlsSecretName }}
  issuerRef:
    name: lets-encrypt
  dnsNames:
    - {{ host }}
