apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ name }}-tls-certificate
spec:
  secretName: {{ tlsSecretName }}
  issuerRef:
    name: lets-encrypt
  dnsNames:
    - {{ host }}
  acme:
    config:
      - dns01:
          provider: route53-dns
        domains:
          - {{ host }}