apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ name }}
  replicas: {{ replicaCount }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      containers:
        - name: {{ name }}-container
          image: {{{ dockerImage }}}
          envFrom:
            - configMapRef:
                name: {{ name }}-config-map
          env:
          {{#secrets}}
            - name: {{ key }}
              valueFrom:
                secretKeyRef:
                  name: {{ name }}-secrets
                  key: {{ key }}
          {{/secrets}}
          ports:
            - containerPort: {{ containerPort }}