apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}-deployment
spec:
  replicas: {{ replicaCount }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      containers:
        - name: {{ name }}-container
          image: {{ dockerImage }}
          ports:
            - containerPort: {{ containerPort }}