apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ name }}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx # In GKE to indicate to use the nginx Ingress controller rather than GCP Ingress controller
spec:
  tls:
    - secretName: {{ tlsSecretName }}
      hosts:
        - {{ host }}
  rules:
    - host: {{ host }}
      http:
        paths:
          - backend:
              serviceName: {{ name }}-service
              servicePort: {{ containerPort }}